config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :newsapi
  resources :pages
  resources :profiles

  root to: 'pages#index'

  devise_for :editors, path: 'editors', :controllers => { registrations: 'devise/registrations' }
  devise_for :users, path: 'users', :controllers => { registrations: 'devise/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  # Relationships
  belongs_to :article
  belongs_to :user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # GET /articles/1/comments
  def index

    @article = Article.find(params[:article_id])
    @comments = @article.comments

    @user = current_user

  end

  # GET /articles/1/comments/2
  def show

    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

  end

  # GET /articles/1/comments/new
  def new

    @article = Article.find(params[:article_id])
    @comment = @article.comments.build

  end

  # POST /articles/1/comments
  def create

    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)

    @comment.user = current_user

    if @comment.save
      # Save the review successfully
      redirect_to article_comments_url(@article, @comment)
    else
      render :action => "new"
    end
  end

  # GET /articles/1/comments/2/edit
  def edit

    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

  end

  # PUT /articles/1/comments/2
  def update

    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      # Save the review successfully
      redirect_to article_comment_url(@article, @comment)
    else
      render :action => "edit"
    end
  end

  # DELETE /articles/1/comments/2
  def destroy

    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_comments_path(@article), notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<!-- Form used in the new and edit pages -->

<%= form_for([@article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error")%>
        prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= f.text_field :content, class: "form-control"  %>
    </p>
  </div>

  <div class="actions">
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<br>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Show', article_comments_path(@article, @comment) %>
</button>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Back', article_comments_path(@article) %>
</button>

app/views/comments/index.html.erb
<% require 'ProfanityFilter' %>

<h1>Comments from Article: <%= ProfanityFilter.check(@article.headline) %></h1>

<!-- View for article comments which is looped through and displayed as a cardview, with the profanity filter called on the input -->
<% for comment in @comments %>
  <div class="card">
    <div class="card-block">
      <h5 class="card-text"> Commented By: <%= comment.user.email %> </h5>
      <p class="card-text"> <%= ProfanityFilter.check(comment.content) %></p>

      <br>

      <!-- Only display, Show Edit, Delete for User -->
      <% if current_user %>

        <button type="button" class="btn btn-outline-primary">
          <%= link_to 'Show', article_comment_path(@article, comment)%>
        </button>

        <button type="button" class="btn btn-outline-primary" style="alignment: right">
          <%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
        </button>

        <button type="button" class="btn btn-outline-primary" style="alignment: right">
          <%= link_to 'Delete', article_comment_path(@article, comment), data: { confirm: 'Are you sure?' } , :method => :delete %>
        </button>

      <% end %>

    </div>
  </div>

<% end %>

<!-- Display Back for both users -->
<% if current_user || current_editor%>

  <button type="button" class="btn btn-outline-primary" style="alignment: right">
    <%= link_to 'Back', article_path(@article) %>
  </button>

<%end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>
<br>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Back', article_comments_path(@article) %>
</button>

app/views/comments/show.html.erb
<% require 'ProfanityFilter' %>

<!-- Displaying comment values with profanity filter called on all user inputs -->
<h1><%= ProfanityFilter.check( @article.headline) %></h1>

<div class="card">
  <div class="card-block">
    <h5 class="card-text"> Commented By: <%= @comment.user.email %> </h5>
    <p class="card-text"> <%= ProfanityFilter.check(@comment.content)  %> </p>

    <br>

    <button type="button" class="btn btn-outline-primary" style="alignment: right">
      <%= link_to 'Edit', edit_article_comment_path(@article, @comment) %>
    </button>

    <button type="button" class="btn btn-outline-primary" style="alignment: right">
      <%= link_to 'Back', article_comments_path(@article) %>
  </button>

  </div>
</div>