config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :newsapi
  resources :pages
  resources :profiles

  root to: 'pages#index'

  devise_for :editors, path: 'editors', :controllers => { registrations: 'devise/registrations' }
  devise_for :users, path: 'users', :controllers => { registrations: 'devise/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  # Relationships
  belongs_to :editor
  has_many :comments

  # Search functionality, compares value in search to values of headline and body content
  def self.search(search)
    if search

      where(["headline LIKE ?", "% #{search}%"])
      where(["body LIKE ?", "% #{search}%"])

    else
      all
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    # Search functionality
    if params[:search]
      @articles = Article.search(params[:search])
    end

  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    @article = Article.find(params[:id])

  end

  # GET /articles/new
  def new
    @article = Article.new

  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    @article = Article.new(article_params)
    @article.editor = current_editor

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:headline, :body)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<!-- Form used in the new and edit pages -->

<%= bootstrap_form_with(model: @article, local: true) do |f| %>
  <%= f.text_field :headline %>
  <%= f.text_area :body  %>
  <%= f.submit %>
<% end %>

<br>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Show', @article %>
</button>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Back', articles_path %>
</button>

app/views/articles/index.html.erb
<% require 'ProfanityFilter' %>

<h1>Public Articles</h1>

<div class="container">

  <br>

  <!-- Search functionality -->
  <%= form_tag articles_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>

    <br>
    <%= submit_tag "Search", class: "btn btn-primary" %>

  <% end %>
  <br>

  <!-- View for articles which is looped through and displayed as a cardview, with the profanity filter called on each input -->
  <% @articles.each do |article| %>
  <div class="card">
    <div class="card-block">
      <h4 class="card-title"> <%= ProfanityFilter.check(article.headline) %> </h4>
      <p class="card-text"> <%= ProfanityFilter.check(article.body) %> </p>
      <h5 class="card-text">Published By: <%= article.editor.email %></h5>

      <br>

      <!-- Display show for both users -->
      <% if current_user || current_editor %>
          <button type="button" class="btn btn-outline-primary">
            <%= link_to 'Show', article %>
          </button>
        <% end %>

      <!-- Only display Edit, Delete for editors -->
      <% if current_editor %>

        <button type="button" class="btn btn-outline-primary" style="alignment: right">
          <%= link_to 'Edit', edit_article_path(article) %>
        </button>

        <button type="button" class="btn btn-outline-primary" style="alignment: right">
          <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        </button>

      <%end %>

    </div>
  </div>
  <% end %>

  <br>

  <!-- Only display New Article for editors -->
  <% if current_editor %>

    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'New Article', new_article_path %>
    </button>

  <%end %>

</div>

<!-- Render in footer partial -->
<%= render 'layouts/footer' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<br>

<button type="button" class="btn btn-outline-primary" style="alignment: right">
  <%= link_to 'Back', articles_path %>
</button>

app/views/articles/show.html.erb
<% require 'ProfanityFilter' %>

<h1>Public Articles</h1>
<br>

<div class="container">

  <!-- Display article data in card view and call profanity filter on each article input -->
  <div class="card">
      <div class="card-block">
        <h4 class="card-title"><%= ProfanityFilter.check(@article.headline) %></h4>
        <p class="card-text"><%= ProfanityFilter.check(@article.body) %></p>
        <h5 class="card-text">Published By: <%= @article.editor.email %></h5>

        <br>

        <button type="button" class="btn btn-outline-primary" style="alignment: right">
          <%= link_to 'Back', articles_path %>
        </button>

      </div>
    </div>

  <br>

  <h2>Article Comments</h2>

  <!-- View for article comments which is looped through and displayed as a cardview, with the profanity filter called on each input -->
  <% @article.comments.each do |comment| %>
    <div class="card">
      <div class="card-block">
        <h5 class="card-text"> Commented By: <%= comment.user.email %> </h5>
        <p class="card-text"> <%=  ProfanityFilter.check(comment.content) %> </p>

        <!-- Only display Edit, Delete for users -->
        <% if current_user %>

          <button type="button" class="btn btn-outline-primary" style="alignment: right">
            <%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
          </button>

          <button type="button" class="btn btn-outline-primary" style="alignment: right">
            <%= link_to 'Delete', article_comment_path(@article, comment), data: { confirm: 'Are you sure?' } , :method => :delete %>
          </button>

        <%end %>
      </div>
    </div>

    <br>

  <% end %>

  <!-- Display show comments for both users -->
  <% if current_user || current_editor%>
    <button type="button" class="btn btn-outline-primary" style="alignment: right">
      <%= link_to 'Show Comments', article_comments_path(@article) %>
    </button>
  <%end %>

  <!-- Only display New Comment for users -->
  <% if current_user %>
    <button type="button" class="btn btn-outline-primary" style="alignment: right">
    <%= link_to 'New Comment', new_article_comment_path(@article) %>
    </button>

  <%end %>
</div>