config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :newsapi
  resources :pages
  resources :profiles

  root to: 'pages#index'

  devise_for :editors, path: 'editors', :controllers => { registrations: 'devise/registrations' }
  devise_for :users, path: 'users', :controllers => { registrations: 'devise/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<!-- Devise alerts-->

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<!-- Footer with links to API sources -->

<br>
<br>

<footer class="page-footer">

  <div class="footer-copyright text-center py-3">© 2020 Copyright, Sources:

    <a href="https://newsapi.org/"> NewsApi </a>
    <a href="https://openweathermap.org/api"> OpenWeather Api </a>

  </div>

</footer>

app/views/layouts/_nav.html.erb
<!-- Navbar, with favicon and both user sign in/ sign up forms linked -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header" style="padding-top: 12px; height: 12px;">
      <a class="navbar-brand">
        <%= image_tag "favicon.png", size: "23x23"%>
        <%= link_to 'NewsWave', root_path , {:style=>'color: #FFFFFF; font-weight: bold;'} %>
      </a>

      <button type="button" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    </div>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="nav navbar-nav">
        <li>

          <% if current_editor ||  current_user%>
            <%= link_to 'Articles', articles_path %>
          <%end %>

        </li>
        <li>
          <% if current_editor ||  current_user%>
            <%= link_to 'Profile', profiles_path %>
          <%end %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right" style="padding-top: 8px;">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <a class="dropdown-item">
              <% if !current_user %>
              <%= link_to 'Sign up as a Reader', new_user_registration_path %>
              <%end %>
            </a>

            <a class="dropdown-item">
              <% if !current_user %>
               <%= link_to 'Sign in as a Reader', new_user_session_path %>
              <% else %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
              <%end %>
            </a>

            <a class="dropdown-item">
              <% if current_user %>
                <%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %>
            <% end %>
            </a>

        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Editor
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a class="dropdown-item">
            <% if !current_editor %>
              <%= link_to 'Sign up as an Editor', new_editor_registration_path %>
            <% end %>
          </a>

          <a class="dropdown-item">
            <% if !current_editor %>
              <%= link_to 'Sign in as an Editor', new_editor_session_path %>
            <% else %>
              <%= link_to 'Sign out', destroy_editor_session_path, method: :delete %>
            <%end %>
          </a>

          <a class="dropdown-item">
            <% if current_editor %>
              <%= link_to "Cancel my account", registration_path(current_editor), data: { confirm: "Are you sure?" }, method: :delete %>
            <% end %>
          </a>

        </div>
      </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- Base HTML page which renders in the nav and devise alerts -->

<!DOCTYPE html>
<html>
<head>
  <title> NewsWave </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css"
        integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd"
        crossorigin="anonymous">
</head>

<%= render 'layouts/nav' %>

<div class="container">

  <body>

  <%= render 'layouts/alerts' %>
  <%= yield %>

  </body>

</div>
</html>